Vagrant.configure("2") do |config|
  config.vm.define :db do |db_config|
    db_config.vm.box = "bento/ubuntu-24.04"
    db_config.vm.hostname = "mysql-server"
    db_config.vm.network :private_network, ip: "192.168.56.11"
    
    db_config.vm.provider "virtualbox" do |vb|
      vb.name   = "msyql-8.0-server"
      vb.memory = "4096"
      vb.cpus   = 2
    end

    db_config.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y
      sudo apt-get upgrade -y
      echo "mysql-server mysql-server/root_password password 12345" | sudo debconf-set-selections
      echo "mysql-server mysql-server/root_password_again password 12345" | sudo debconf-set-selections
      sudo apt-get install -y mysql-server-8.0
      sudo sed -i 's/bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
      sudo service mysql restart

      DB_NAME="loja_schema"
      DB_USER="vinicius"
      DB_PASS="12345"
      DB_ROOT_PASS="12345"

      mysql -u root -p"${DB_ROOT_PASS}" -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
      mysql -u root -p"${DB_ROOT_PASS}" -e "CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';"
      mysql -u root -p"${DB_ROOT_PASS}" -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';"
      mysql -u root -p"${DB_ROOT_PASS}" -e "FLUSH PRIVILEGES;"
    SHELL
  end

  config.vm.define :web do |web_config|
    web_config.vm.box = "bento/ubuntu-24.04"
    web_config.vm.hostname = "tomcat-server"
    web_config.vm.network :private_network, ip: "192.168.56.10"
    web_config.vm.network "forwarded_port", guest: 8080, host: 8080   
      web_config.vm.network "forwarded_port", guest: 8443, host: 8443   

    web_config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    web_config.vm.provider "virtualbox" do |vb|
      vb.name   = "tomcat10-server"
      vb.memory = "2048"
      vb.cpus   = 2
    end

    web_config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get upgrade -y

      apt-get install -y openjdk-21-jdk

      echo 'JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"'       >> /etc/environment
      echo 'export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"' >> /etc/profile.d/java.sh
      echo 'export PATH=$JAVA_HOME/bin:$PATH'                       >> /etc/profile.d/java.sh
      source /etc/environment

      apt-get install -y tomcat10 tomcat10-admin

    cat > /etc/tomcat10/tomcat-users.xml <<EOF
<?xml version='1.0' encoding='utf-8'?>
<tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">

  <role rolename="manager-gui"/>
  <role rolename="manager-script"/>
  <role rolename="admin-gui"/>

  <user username="admin"
        password="admin123"
        roles="manager-gui,manager-script,admin-gui"/>
</tomcat-users>
EOF

    systemctl enable tomcat10
    systemctl start tomcat10

    java -version
    systemctl status tomcat10 --no-pager
    
    cp /vagrant/sources/*.war /var/lib/tomcat10/webapps
  SHELL
  end
end